version: '3.8'
services:
  backend:
    build: ./python-backend
    ports:
      - "8888:8888"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./python-backend:/app
    networks:
      - localnet
  ui:
    build: ./ui
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=7777
    depends_on:
      - backend
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
