version: '3.8'
services:
  backend:
    build: ./python-backend
    ports:
      - "8888:8888"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./python-backend:/app
  ui:
    build: ./ui
    ports:
      - "3333:3333"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3333
    depends_on:
      - backend
